pipeline {
    agent any
 
    stages {
        stage('Checkout') {
            steps {
                // Checkout the current branch
                checkout scm
            }
        }
 
        stage('Restore NuGet Packages') {
            steps {
                script {
                    // Restore the NuGet packages
                    bat 'nuget restore ConsoleApp1.sln'
                }
            }
        }
 
        stage('Build') {
            steps {
                script {
                    // Build the Visual Studio solution (.sln file)
                    bat '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe" ConsoleApp1.sln "'
                }
            }
        }
    }
 
    post {
        always {
            // Archive build artifacts
            archiveArtifacts artifacts: '**/bin/**/*.dll', allowEmptyArchive: true
        }
        success {
            echo 'Build and tests were successful!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}